import os
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.getenv("BOT_TOKEN")
TMDB_API_KEY = os.getenv("TMDB_API_KEY")
RUTRACKER_USERNAME = os.getenv("RUTRACKER_USERNAME")
RUTRACKER_PASSWORD = os.getenv("RUTRACKER_PASSWORD")
OPENSUBTITLES_API_KEY = os.getenv("OPENSUBTITLES_API_KEY")
OPENSUBTITLES_USERNAME = os.getenv("OPENSUBTITLES_USERNAME", "bot")
OPENSUBTITLES_PASSWORD = os.getenv("OPENSUBTITLES_PASSWORD", "bot")
BOT_API_SERVER_URL = os.getenv("BOT_API_SERVER_URL")
MAX_FILE_SIZE_MB = int(os.getenv("MAX_FILE_SIZE_MB", "1900"))
MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024
DOWNLOAD_DIR = os.getenv("DOWNLOAD_DIR", "./downloads")
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
SUBTITLE_FONT_SIZE = int(os.getenv("SUBTITLE_FONT_SIZE", "24"))
SUBTITLE_LANGUAGE = os.getenv("SUBTITLE_LANGUAGE", "rus")

os.makedirs(DOWNLOAD_DIR, exist_ok=True)
